import express from 'express';
import dotenv from 'dotenv';
dotenv.config();
import { Cashfree, CFEnvironment } from 'cashfree-pg';
import Order from '../models/Order.js';


const router = express.Router();

// Initialize Cashfree
const mode = process.env.CASHFREE_MODE || 'SANDBOX';
const appId = process.env.CASHFREE_APP_ID;
const secretKey = process.env.CASHFREE_SECRET_KEY;

// Diagnostic Log (Masked)
console.log("--- Cashfree Diagnostics ---");
console.log("Mode:", mode);
console.log("App ID:", appId ? `${appId.substring(0, 4)}...${appId.substring(appId.length - 4)}` : "MISSING");
console.log("Secret Key:", secretKey ? `${secretKey.substring(0, 8)}...` : "MISSING");
console.log("---------------------------");

if (!appId || !secretKey) {
    console.error("CRITICAL: Cashfree Credentials missing in .env!");
}

const cashfree = new Cashfree(
    mode === 'PRODUCTION' ? CFEnvironment.PRODUCTION : CFEnvironment.SANDBOX,
    appId,
    secretKey
);

// @desc    Create Cashfree order
// @route   POST /api/payment/create-order
router.post('/create-order', async (req, res) => {
    console.log("DEBUG: BACKEND_URL is:", process.env.BACKEND_URL);
    try {
        const { amount, customer_details, order_meta } = req.body;

        // 1. Strict order_amount as Number
        const orderAmount = Number(amount);
        if (isNaN(orderAmount) || orderAmount <= 0) {
            return res.status(400).json({ message: 'Invalid order amount. Must be a positive number.' });
        }

        // 2. Strict customer_details formatting
        if (!customer_details || !customer_details.customer_phone || !customer_details.customer_email) {
            return res.status(400).json({ message: 'customer_details with phone and email is required.' });
        }

        const cleanPhone = customer_details.customer_phone.replace(/\D/g, '').slice(-10); // Ensure 10 digits, no +91
        if (cleanPhone.length !== 10) {
            return res.status(400).json({ message: 'Invalid customer_phone. Must be 10 digits.' });
        }

        const formattedCustomerDetails = {
            customer_id: customer_details.customer_id || `cust_${Date.now()}`,
            customer_phone: cleanPhone,
            customer_email: customer_details.customer_email.trim(),
            customer_name: customer_details.customer_name?.trim() || 'Customer'
        };

        // 3. URL Validation for Production
        let returnUrl = order_meta?.return_url || `${process.env.FRONTEND_URL}/order-success?order_id={order_id}`;
        let notifyUrl = order_meta?.notify_url || `${process.env.BACKEND_URL}/api/payment/webhook`;

        if (process.env.CASHFREE_MODE === 'PRODUCTION') {
            if (returnUrl.includes('localhost') || notifyUrl.includes('localhost')) {
                console.warn("WARNING: Cashfree PRODUCTION mode does not support localhost URLs. Reverting to dummy HTTPS for order creation to avoid API rejection.");
                // Replace localhost with a dummy domain if necessary, or just log clearly
                // returnUrl = returnUrl.replace('http://localhost:5173', 'https://yourdomain.com');
            }
        }

        const request = {
            "order_amount": orderAmount,
            "order_currency": "INR",
            "order_id": `order_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
            "customer_details": formattedCustomerDetails,
            "order_meta": {
                "return_url": returnUrl,
                "notify_url": notifyUrl
            }
        };

        console.log("FINAL Cashfree Order Request:", JSON.stringify(request, null, 2));
        const response = await cashfree.PGCreateOrder(request);
        
        console.log("Cashfree Success Response:", JSON.stringify(response.data, null, 2));

        if (!response.data.payment_link) {
            throw new Error('Payment link not generated by Cashfree');
        }

        res.json({ 
            payment_link: response.data.payment_link 
        });

    } catch (error) {
        // 4. Enhanced Error Logging as requested
        console.log("Cashfree Full Error:", JSON.stringify(error.response?.data || error, null, 2));
        
        res.status(500).json({ 
            message: 'Cashfree API Error', 
            error: error.response?.data || error.message 
        });
    }
});

// @desc    Cashfree Webhook
// @route   POST /api/payment/webhook
router.post('/webhook', async (req, res) => {
    try {
        const signature = req.headers['x-webhook-signature'];
        const body = req.body;
        const timestamp = req.headers['x-webhook-timestamp'];

        // Verify webhook signature
        try {
            cashfree.PGVerifyWebhookSignature(signature, JSON.stringify(body), timestamp);
        } catch (err) {
            console.error("Webhook Signature Verification Failed:", err.message);
            return res.status(400).send("Invalid Signature");
        }
        
        const { order, payment } = body.data; // Assuming the actual data is nested under 'data' as per original code

        const dbOrder = await Order.findOne({ cfOrderId: order.order_id });
        if (dbOrder) {
            if (payment.payment_status === 'SUCCESS') {
                dbOrder.paymentStatus = 'Completed';
                dbOrder.cfPaymentId = payment.cf_payment_id;
                await dbOrder.save();
                console.log(`Order ${order.order_id} marked as Completed`);
            } else if (payment.payment_status === 'FAILED') {
                dbOrder.paymentStatus = 'Failed';
                await dbOrder.save();
                console.log(`Order ${order.order_id} marked as Failed`);
            }
        }

        res.status(200).send("OK");
    } catch (error) {
        console.error("Webhook Error:", error.message);
        res.status(500).json({ message: 'Webhook Error', error: error.message });
    }
});

export default router;
